config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'
  resources :dashboard, only:[:index]
  resources :applications

  devise_for :users, path_names: {
    sign_up: 'register'
  }
  

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :user
  belongs_to :college
end

app/models/college.rb
class College < ActiveRecord::Base
  has_many :applications
  has_many :users, through: :applications
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :applications
  has_many :colleges, through: :applications
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController

  def index
    @applications = Application.all
  end

  def show
  end

  def new
    @application = Application.new
  end

  def edit
  end

  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render :show, status: :created, location: @application }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def application_params
      params.fetch(:application, {})
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  helper_method :resource_name, :resource, :devise_mapping

  def resource_name
    :user
  end
  
  def resource
    @resource ||= User.new
  end
  
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email)
    end
end

app/views/applications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Applications</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<%= form_for@application, html: { class: 'form'} do |f| %>
  <div class="field form-group">
    <%= f.label :college %><br />
  <% options = options_from_collection_for_select(College.all, 'id', 'name') %>
  <%= f.select :id, options, :input_html => { class: "form-control" } %>

  <div class="actions btn btn-default">
    <%= f.submit "Add to Application List", class: 'form-control' %>
  </div>
<% end %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>

app/views/dashboard/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3">Welcome to Your College Applications Dashboard!</h1>
    <p class="lead">Easily track and manage your college applications, all in one place.</p>
  </div>
</div>

<div class="management-links">
  <%= link_to "Manage Account Settings", edit_user_registration_path, class: "btn btn-primary"%>
  <%= link_to "Manage My Applications", applications_path, class: "btn btn-primary js-open-apps-manager" %>
</div>
<div class="manage-applications">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collegeapptracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice top-notice"><%= notice %></p>
  <p class="alert top-notice"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: 'devise-links' %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Register", new_registration_path(resource_name), class: 'devise-links' %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'devise-links' %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: 'devise-links' %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: 'devise-links' %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: 'devise-links' %><br />
  <% end -%>
<% end -%>